### ISSUE TITLE
Improve structure

### ISSUE THREAD

**Issue by Bart-Edelbroek** [ZahraPayandeh/Zahra_project#2]
Please improve the structure of your repo by adding folders, for example containing all the .tif images, all the example output etc.

**Comment by Bart-Edelbroek** [comment]
Also, the structure written in your README.md is fine, but it doesn't match what is in the repo:

main_script.py Main Python script with image analysis and result generation
results.pdf PDF file containing analysis results
nucleus_distribution.png Histogram of nucleus area distributions (saved from the script)
images/ Folder containing nucleus24 and nucleus38 images

**Comment by ZahraPayandeh** [comment]
Thank you so much for your feedback.
I was wondering if can i send you my edited version till 15th of November?
Best
Zahra

________________________________

**Comment by Bart-Edelbroek** [comment]
Hey,

You can update the repo here, and then let me know when it is updated. Then I'll have another look. The 15th of Nov is fine by me.

Best,

Bart

**Comment by ZahraPayandeh** [comment]
Hi,
Thank you for your feedback,
I tried to edit the git hub parts according your comments.
Here is the link https://github.com/ZahraPayandeh/Zahra_project
I hope they are acceptable now.
Best
Zahra

________________________________
