### ISSUE TITLE
Images are empty

### ISSUE THREAD

**Issue by Bart-Edelbroek** [ZahraPayandeh/Zahra_project#5]
It seems that when you updated your images, that the data was lost (see; <https://github.com/ZahraPayandeh/Zahra_project/commit/9b12c18300dbd1c4ce639fba16cfde58c4d5cc72>)

If the images were too large, you could maybe choose to upload fewer images per group, or decrease their size?

**Comment by ZahraPayandeh** [comment]
Hi 
thank you for your comment.  i uploaded the images one by one. Group A is 24. and Group B is 38. 
Thank you

**Comment by ZahraPayandeh** [comment]
now i managed to put all images in their folders.
Best
Zahra

**Comment by Bart-Edelbroek** [comment]
Good job!

**Comment by ZahraPayandeh** [comment]
Hi,
I edited the git hub parts according to your comments. i was wondering if it is acceptable now or should i need more edit?
Thank you for your feedback
Best
Zahra

________________________________

**Comment by Bart-Edelbroek** [comment]
Hey,

You’re almost there! Now that you defined the parse_arguments() function you also have to run it, e.g.:

`args = parse_arguments()`

Then to get the paths that the user has input you would use e.g.:

`nucleus24_folder = args.groupA`

You could then from there execute the code as you already have.
It would mean that if someone ran the code below, that it would find the images in the Images folder:

python --groupA Images/groupA --groupB Images/groupB

Whereas if someone ran the code here, it would look in the downloads folder:

python --groupA ~/Downloads/downloaded_gA --groupB ~/Downloads/downloaded_gA

Give it a go and let me know if you need help!

Best,

bart


From: ZahraPayandeh ***@***.***>
Date: Tuesday, 3 December 2024 at 19:19
To: ZahraPayandeh/Zahra_project ***@***.***>
Cc: Bart-Edelbroek ***@***.***>, State change ***@***.***>
Subject: Re: [ZahraPayandeh/Zahra_project] Images are empty (Issue #5)
Hi,
I edited the git hub parts according to your comments. i was wondering if it is acceptable now or should i need more edit?
Thank you for your feedback
Best
Zahra

________________________________

**Comment by ZahraPayandeh** [comment]
Thank you
It is done.
Best Regards
Zahra

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bart-Edelbroek** [comment]
Good job! You have passed all the requirements for the project.
I’m happy you were able to persevere

Best regards,

Bart

From: ZahraPayandeh ***@***.***>
Date: Tuesday, 3 December 2024 at 21:29
To: ZahraPayandeh/Zahra_project ***@***.***>
Cc: Bart-Edelbroek ***@***.***>, State change ***@***.***>
Subject: Re: [ZahraPayandeh/Zahra_project] Images are empty (Issue #5)
Thank you
It is done.
Best Regards
Zahra

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
